# Generated by Django 4.1.7 on 2023-05-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
