# Generated by Django 4.1.7 on 2023-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_title",
            field=models.ImageField(
                blank=True, default="titulo.png", null=True, upload_to=""
            ),
        ),
    ]
