# Generated by Django 4.1.7 on 2023-04-19 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apellidos',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre(s)'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nombre del usuario')),
                ('apell', models.CharField(max_length=255, verbose_name='Apellidos del paciente')),
                ('edad', models.CharField(max_length=255, verbose_name='Edad del paciente')),
                ('telc', models.CharField(max_length=255, verbose_name='Teléfono celular')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('seguro', models.CharField(max_length=255, verbose_name='Seguro Medico')),
                ('profile_pic', models.ImageField(blank=True, default='perfil1.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
