# Generated by Django 4.1.7 on 2023-03-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_expediented_idpg_expedienteo_idpg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediented",
            name="NDiente",
            field=models.CharField(max_length=255, verbose_name="Nombre del diente"),
        ),
        migrations.AlterField(
            model_name="expedienteg",
            name="idPg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario paciente",
            ),
        ),
    ]
