# Generated by Django 4.1.7 on 2023-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_apellidos_alter_profile_nombre_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrtname', models.CharField(max_length=255, verbose_name='Nombre del usuario')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellidos del paciente')),
                ('opinion', models.CharField(max_length=255, verbose_name='opinion')),
            ],
        ),
    ]
